optimizer:
    sgd:
        momentum: 0.8  # overwite some configs from default

scheduler:
    name: "reduce_lr_on_plateau"  # use 'reduce_lr_on_plateau' as scheduler

    reduce_lr_on_plateau:  # overwite some configs from default
        mode: max
        factor: 0.2